name: Translation Helper

on:
  pull_request_target:
    types: [opened]
  issues:
    types: [opened]

jobs:
  translate:
    runs-on: ubuntu-latest
    steps:
      - uses: hnwyllmm/translation-helper@main
