name: Translation Helper

on:
  pull_request_target:
    types: [opened]
  issues:
    types: [opened]
  issue_comment: 
    types: [created]

jobs:
  translate:
    runs-on: ubuntu-latest
    steps:
      - uses: hnwyllmm/translation-helper@e3c6feb8f0d890098cd02d5548610f89f62e323d
