name: Translation Helper

on:
  pull_request_target:
    types: [opened]
  issues:
    types: [opened]
  issue_comment: 
    types: [created]

jobs:
  translate:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: usthe/issues-translate-action@v2.7
        with:
          IS_MODIFY_TITLE: true
          BOT_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
