name: Translation Helper

on:
  pull_request_target:
    types: [opened]
  issues:
    types: [opened]
  issue_comment: 
    types: [created]

jobs:
  translate:
    runs-on: ubuntu-latest
    steps:
      - uses: hnwyllmm/issue-transation-helper@main
